# Generated by Django 5.2.3 on 2025-06-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('classification_ai', models.CharField(max_length=20)),
                ('confidence_ai', models.FloatField()),
                ('classification_user', models.CharField(max_length=20)),
                ('original_text', models.TextField()),
                ('match_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='requirements_classifier.documents')),
            ],
        ),
    ]
